//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniLoLProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinLoLRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MinLoLRole()
        {
            this.MinLoLChampions = new HashSet<MinLoLChampion>();
        }
    
        public int ChampRoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MinLoLChampion> MinLoLChampions { get; set; }
    }
}
