//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniLoLProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinLoLChampion
    {
        public string Name { get; set; }
        public string Title { get; set; }
        public string ChampIcon { get; set; }
        public string ChampPic { get; set; }
        public string ChampBio { get; set; }
        public int ChampID { get; set; }
        public int UltimateID { get; set; }
        public int ChampRoleID { get; set; }
    
        public virtual MinLoLRole MinLoLRole { get; set; }
        public virtual MinLoLUltimate MinLoLUltimate { get; set; }
    }
}
