//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniLoLProject.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MinLoLChampsEntities : DbContext
    {
        public MinLoLChampsEntities()
            : base("name=MinLoLChampsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MinLoLChampion> MinLoLChampions { get; set; }
        public virtual DbSet<MinLoLRole> MinLoLRoles { get; set; }
        public virtual DbSet<MinLoLUltimate> MinLoLUltimates { get; set; }
    }
}
